# SPDX-License-Identifier: FSFAP
# Copyright (C) 2023 Edith Coates
# Copyright (C) 2023 Colin B. Macdonald

# If you are working with VSC and wish to start up a
# docker/django debugging server, copy + uncomment this text into
# plom/.vscode/launch.json
# {
#     "version": "0.2.0",
#     "configurations": [
#         {
#             "name": "Python: Django",
#             "type": "python",
#             "request": "attach",
#             "pathMappings": [
#                 {
#                     "localRoot": "${workspaceFolder}/plom_server",
#                     "remoteRoot": "/code"
#                 }
#             ],
#             "port": 3000,
#             "host": "127.0.0.1"
#         },
#     ]
# }

# can comment out the 3000:3000 below if not using the above
services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    depends_on:
      - web
  web:
    image: "plomgrading/server"
    ports:
      - ${PORT}:8000
      # 3000:3000
    expose:
      - ${PORT}
    command: bash -c "cd /src/plom_server; ./docker_run.sh"
    # TODO: those on Fedora, might need a :z at the end
    volumes:
      - ./my_exam:/exam:z
    depends_on:
      - postgres
    environment:
      - "PLOM_MEDIA_ROOT=/exam/media_root"
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=plom_db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  postgres_data:
