# SPDX-License-Identifier: FSFAP
# Copyright (C) 2023 Edith Coates
# Copyright (C) 2023 Colin B. Macdonald

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    depends_on:
      - web
  web:
    image: "plomgrading/server"
    # ports:
    #   - ${PORT}:8000
    # expose:
    #   - ${PORT}
    ports:
      - 8000:8000
    expose:
      - 8000
    command: bash -c "cd /src/plom_server; ./docker_run.sh"
    # mount a local dir for storage
    # TODO: those on Fedora, might need a :z at the end
    # volumes:
    #   - ./my_exam:/exam:z
    depends_on:
      - postgres
    environment:
      - "PLOM_MEDIA_ROOT=/exam/media_root"
      - "PLOM_DATABASE_HOSTNAME=postgres"
  postgres:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - "POSTGRES_HOST_AUTH_METHOD=trust"
      - "POSTGRES_DB=plom_db"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=postgres"

volumes:
  postgres_data:
