# Generated by Django 5.1.7 on 2025-06-25 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("Base", "0001_initial"),
        ("Papers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionClusteringChore",
            fields=[
                (
                    "hueytasktracker_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="Base.hueytasktracker",
                    ),
                ),
                ("question_idx", models.PositiveIntegerField()),
                ("version", models.PositiveIntegerField()),
                ("top", models.FloatField()),
                ("left", models.FloatField()),
                ("bottom", models.FloatField()),
                ("right", models.FloatField()),
            ],
            bases=("Base.hueytasktracker",),
        ),
        migrations.CreateModel(
            name="QVCluster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_idx", models.PositiveIntegerField()),
                ("version", models.PositiveIntegerField()),
                ("clusterId", models.IntegerField()),
                ("top", models.FloatField()),
                ("left", models.FloatField()),
                ("bottom", models.FloatField()),
                ("right", models.FloatField()),
            ],
            options={
                "unique_together": {("question_idx", "version", "clusterId")},
            },
        ),
        migrations.CreateModel(
            name="QVClusterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "paper",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Papers.paper"
                    ),
                ),
                (
                    "qv_cluster",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="QuestionClustering.qvcluster",
                    ),
                ),
            ],
        ),
    ]
