# Generated by Django 5.1.7 on 2025-06-25 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("QuestionClustering", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="questionclusteringchore",
            name="page_num",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="qvcluster",
            name="page_num",
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
    ]
