# Generated by Django 5.1.7 on 2025-07-15 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "QuestionClustering",
            "0002_questionclusteringchore_page_num_qvcluster_page_num",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="questionclusteringchore",
            name="clustering_model",
            field=models.CharField(
                choices=[
                    ("mcq", "Multiple choice (A-F, a-f)"),
                    ("hme", "Generic handwritten math expression"),
                ],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
