# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2023-2024 Andrew Rechnitzer

# Solution spec for 'Midterm Demo using Plom'

numberOfPages = 5
    
# for question 1
[[solution]]
pages = [3]
        
# for question 2
[[solution]]
pages = [4]
        
# for question 3
[[solution]]
pages = [5]
        
