# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2024 Andrew Rechntizer

[[rubric]]
kind = "relative"
display_delta = "+2"
value = 2.0
out_of = 0.0
text = "correct limit"
tags = "demo"
meta = "Student evaluated limit correctly"
question = 1
username = "manager"

[[rubric]]
kind = "relative"
display_delta = "+1"
value = 1.0
out_of = 0.0
text = "right idea, but be careful"
tags = "demo"
meta = "Student made small arithmetic mistake when computing limit"
question = 1
username = "manager"

[[rubric]]
kind = "relative"
display_delta = "-2"
value = -2.0
out_of = 0.0
text = "substantial error"
tags = "demo"
meta = "Student made substantial error when computing limit"
question = 1
username = "manager"

[[rubric]]
kind = "relative"
display_delta = "-2"
value = -2.0
out_of = 0.0
text = "wrong limit at infinity"
tags = "demo"
meta = "Student did not rearrange correctly to compute infinite limit"
question = 1
username = "manager"

[[rubric]]
kind = "relative"
display_delta = "-2"
value = -2.0
out_of = 0.0
text = "must simplify absolute value"
tags = "demo"
meta = "Student forgot to simplify abs value before taking limit"
question = 1
username = "manager"


[[rubric]]
kind = "relative"
display_delta = "-1"
value = -1.0
out_of = 0.0
text = "careful - minor error"
tags = "demo"
meta = "Student made small arithmetic mistake when computing limit"
question = 1
username = "manager"

[[rubric]]
kind = "relative"
display_delta = "-1"
value = -1.0
out_of = 0.0
text = "this does not follow"
tags = "demo"
meta = "Student made logical error from one line to the next"
question = 1
username = "manager"

[[rubric]]
kind = "neutral"
display_delta = "."
value = 0.0
out_of = 0.0
text = "be careful"
tags = "demo"
meta = "Student made an inconsequential error."
question = 1
username = "manager"

[[rubric]]
kind = "neutral"
display_delta = "."
value = 0.0
out_of = 0.0
text = "hard to read"
tags = "demo"
meta = "Student handwriting is making marking hard"
question = 1
username = "manager"


